version: 1

defaults:
  variable: &variable_defaults
    git_host: 'github.com'
    git_org: 'kumak1'
    git_repo: ''
    db_host: 'db'
    db_port: '3306'
    db_user: 'root'
    db_database: 'db'
  string_builder: &string_builder_defaults
    name: 'string_builder'
    work_dir: '`ghq root`'
    run: '{command}'
  shell: &shell_defaults
    name: 'shell'
    work_dir: '`ghq root`'
    run: '{command}'
  docker: &docker_defaults
    name: 'docker'
    work_dir: '`ghq root`/{git_host}/{git_org}/{git_repo}'
    container: ''
    run: 'docker-compose run {container} /bin/bash -c "{command}"'
    build: 'docker-compose build'
    up: 'docker-compose up -d'
    down: 'docker-compose down'
  git: &git_defaults
    env:
      <<: *shell_defaults
    run: '{command}'
    setup: 'ghq get git@{git_host}:{git_org}/{git_repo}.git'
    update: 'ghq get git@{git_host}:{git_org}/{git_repo}.git && cd `ghq root`/{git_host}/{git_org}/{git_repo} && git switch master && git pull'
  php: &php_defaults
    env:
      <<: *docker_defaults
    run: '{command}'
    setup: 'php -d detect_unicode=Off composer.phar install'
    update: 'php -d detect_unicode=Off composer.phar install'
    test: 'cd ./tests && ../vendor/bin/phpunit'
  ruby: &ruby_defaults
    env:
      <<: *docker_defaults
    run: '{command}'
    setup: 'bundle install'
    update: 'bundle install'
    test: 'bundle exec rspec --color'
  node: &node_defaults
    env:
      <<: *docker_defaults
    run: '{command}'
    setup: 'npm install'
    update: 'npm install'
    test: 'npm test'

roles:
  test_role:
    variable:
      <<: *variable_defaults
      git_repo: 'kumaoche'
    git:
      <<: *git_defaults
    docker:
      <<: *docker_defaults

