presets:
  environment:
    git_host: github.com
    git_org:
    git_repo:
  shell:
    working_dir: '`ghq root`/{git_host}/{git_org}/{git_repo}'
    run: '{command}'
    build:
    up:
    down:
  docker:
    container_name:
    working_dir: '`ghq root`/{git_host}/{git_org}/{git_repo}'
    run: docker-compose run -rm {container} /bin/bash -c "{command}"
    build: docker-compose build
    up: docker-compose up -d
    down: docker-compose down
  git:
    run: '{command}'
    setup: ghq get git@{git_host}:{git_org}/{git_repo}.git
    update: ghq get git@{git_host}:{git_org}/{git_repo}.git && cd `ghq root`/{git_host}/{git_org}/{git_repo} && git switch master && git pull
    repo_dir: `ghq root`/{git_host}/{git_org}/{git_repo}
  php:
    run: '{command}'
    setup: php -d detect_unicode=Off composer.phar install
    update: php -d detect_unicode=Off composer.phar install
    test: ./vendor/bin/phpunit
  ruby:
    run: '{command}'
    setup: bundle install
    update: bundle install
    test: bundle exec rspec --color
  node:
    run: '{command}'
    setup: npm install
    update: npm install
    test: npm test
